use crate::resources::*;
use std::path::Path;

/// Generate Terraform files organized by service directory
pub fn generate_all(resources: &AllResources, output: &Path, region: &str) -> anyhow::Result<()> {
    std::fs::create_dir_all(output)?;

    // Provider file at root
    let provider = format!(r#"terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{}"
}}
"#, region);
    std::fs::write(output.join("provider.tf"), provider)?;

    // Generate per-service directory
    let mut all_imports = Vec::new();
    all_imports.push("#!/bin/bash".to_string());
    all_imports.push("# Generated by infra-import".to_string());
    all_imports.push("# Run this to import existing resources into Terraform state".to_string());
    all_imports.push("set -e".to_string());
    all_imports.push(String::new());

    for svc in &resources.services {
        if svc.count() == 0 { continue; }

        let dir = output.join(&svc.service_name);
        std::fs::create_dir_all(&dir)?;

        // Generate .tf file for this service
        let mut tf = String::new();
        let mut svc_imports = Vec::new();

        for r in &svc.resources {
            let tf_name = sanitize_name(&r.name, &r.id);
            tf.push_str(&generate_resource_block(&r.tf_type, &tf_name, &r.attributes));
            tf.push('\n');

            // Import command
            let import_id = get_import_id(&r.tf_type, &r.id);
            svc_imports.push(format!(
                "terraform import {}.{} {}",
                r.tf_type, tf_name, import_id
            ));
        }

        // Write the .tf file
        let filename = format!("{}.tf", svc.service_name);
        std::fs::write(dir.join(&filename), &tf)?;

        // Accumulate imports
        all_imports.push(format!("# --- {} ---", svc.service_name));
        all_imports.extend(svc_imports);
        all_imports.push(String::new());
    }

    all_imports.push("echo \"\"".to_string());
    all_imports.push("echo \"✅ Import complete. Run 'terraform plan' to verify zero diff.\"".to_string());

    std::fs::write(output.join("import.sh"), all_imports.join("\n"))?;

    Ok(())
}

fn generate_resource_block(tf_type: &str, name: &str, attrs: &serde_json::Value) -> String {
    let mut block = format!("resource \"{}\" \"{}\" {{\n", tf_type, name);

    if let Some(obj) = attrs.as_object() {
        for (key, val) in obj {
            // Skip complex nested objects for now — just do scalars
            match val {
                serde_json::Value::String(s) => {
                    if !s.is_empty() {
                        block.push_str(&format!("  {} = \"{}\"\n", key, s.replace('"', "\\\"")));
                    }
                }
                serde_json::Value::Number(n) => {
                    block.push_str(&format!("  {} = {}\n", key, n));
                }
                serde_json::Value::Bool(b) => {
                    block.push_str(&format!("  {} = {}\n", key, b));
                }
                serde_json::Value::Array(arr) => {
                    let items: Vec<String> = arr.iter().filter_map(|v| {
                        v.as_str().map(|s| format!("\"{}\"", s))
                    }).collect();
                    if !items.is_empty() {
                        block.push_str(&format!("  {} = [{}]\n", key, items.join(", ")));
                    }
                }
                serde_json::Value::Object(map) => {
                    // Tags
                    if key == "tags" && !map.is_empty() {
                        block.push_str("  tags = {\n");
                        for (tk, tv) in map {
                            if let Some(s) = tv.as_str() {
                                block.push_str(&format!("    \"{}\" = \"{}\"\n", tk, s));
                            }
                        }
                        block.push_str("  }\n");
                    }
                }
                _ => {}
            }
        }
    }

    block.push_str("}\n");
    block
}

/// Get the correct import ID format for each resource type
fn get_import_id(tf_type: &str, id: &str) -> String {
    match tf_type {
        // Some resources need special import formats
        "aws_eks_node_group" => {
            // format: cluster_name:node_group_name
            id.replace(':', "/")
        }
        "aws_eks_addon" => {
            // format: cluster_name:addon_name
            id.replace(':', "/")
        }
        "aws_route53_zone" => {
            // strip /hostedzone/ prefix
            id.trim_start_matches("/hostedzone/").to_string()
        }
        // Most resources just use their ID directly
        _ => id.to_string(),
    }
}

fn sanitize_name(name: &str, fallback: &str) -> String {
    let src = if name.is_empty() { fallback } else { name };
    let clean: String = src.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    let trimmed = clean.trim_matches('_').to_string();
    if trimmed.is_empty() { "unnamed".to_string() } else { trimmed }
}
